# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Web Call Center
repo_name: grey-dev-0/web-call-center
repo_url: https://github.com/grey-dev-0/web-call-center
edit_uri: ""
theme:
  name: material
  icon:
    logo: material/signal-variant
  palette:
    scheme: dark
    primary: blue grey
    accent: blue
  features:
    - navigation.top
    - navigation.expand
    - search.highlight
plugins:
  - include-markdown
  - search
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      use_pygments: false
extra_javascript:
  - highlight.min.js
  - highlight.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.6.0/styles/github.min.css
  - extra.css
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/theultragrey
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/theultragrey
    - icon: fontawesome/brands/github
      link: https://github.com/grey-dev-0
copyright: Copyright &copy; 2022 Mohyaddin Saleh
